-- AlterTable
ALTER TABLE `User` ADD COLUMN `agoraId` VARCHAR(191) NULL,
    ADD COLUMN `avatar` VARCHAR(191) NULL DEFAULT 'users/default.png',
    ADD COLUMN `biographyImage` TEXT NULL,
    ADD COLUMN `birthday` DATETIME(3) NULL,
    ADD COLUMN `commentEmailNotifications` TINYINT NOT NULL DEFAULT 1,
    ADD COLUMN `country` TEXT NULL,
    ADD COLUMN `displayOnTrainersList` TINYINT NOT NULL DEFAULT 0,
    ADD COLUMN `emailVerifiedAt` DATETIME(3) NULL,
    ADD COLUMN `externalAvatar` TEXT NULL,
    ADD COLUMN `facebookId` VARCHAR(191) NULL,
    ADD COLUMN `feePercentage` INTEGER NULL DEFAULT 0,
    ADD COLUMN `getresponseTags` VARCHAR(191) NULL,
    ADD COLUMN `googleId` VARCHAR(191) NULL,
    ADD COLUMN `gymwolfSession` VARCHAR(191) NULL,
    ADD COLUMN `height` INTEGER NULL,
    ADD COLUMN `hideNameFromLeaderboards` TINYINT NULL,
    ADD COLUMN `languageId` INTEGER NULL DEFAULT 1,
    ADD COLUMN `lastLogin` DATETIME(3) NULL,
    ADD COLUMN `linkOgImage` VARCHAR(191) NULL,
    ADD COLUMN `monthlyNews` SMALLINT NOT NULL DEFAULT 1,
    ADD COLUMN `notifications` TEXT NULL,
    ADD COLUMN `password` VARCHAR(191) NULL,
    ADD COLUMN `profileDesc` TEXT NULL,
    ADD COLUMN `profilePic` TEXT NULL,
    ADD COLUMN `programUnitInfoEmailNotifications` TINYINT NOT NULL DEFAULT 1,
    ADD COLUMN `rememberToken` TEXT NULL,
    ADD COLUMN `roleId` INTEGER NULL,
    ADD COLUMN `sex` VARCHAR(191) NULL,
    ADD COLUMN `showIntro` TINYINT NULL DEFAULT 1,
    ADD COLUMN `simpleLink` VARCHAR(191) NULL,
    ADD COLUMN `sportIdAssessToken` TEXT NULL,
    ADD COLUMN `sportIdEmail` VARCHAR(191) NULL,
    ADD COLUMN `sportIdId` VARCHAR(191) NULL,
    ADD COLUMN `sportIdRefreshToken` TEXT NULL,
    ADD COLUMN `timezone` VARCHAR(191) NULL,
    ADD COLUMN `totalVideoViews` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `trainerChannelImage` VARCHAR(191) NULL,
    ADD COLUMN `trainerIframeIntro` TEXT NULL,
    ADD COLUMN `trainerNotification` TEXT NULL,
    ADD COLUMN `trainerUnlocked` TINYINT NULL,
    ADD COLUMN `trainerWelcomeDesc` TEXT NULL,
    ADD COLUMN `trainerWelcomeTitle` VARCHAR(191) NULL,
    ADD COLUMN `trialEnd` SMALLINT NULL,
    ADD COLUMN `userCredit` DOUBLE NOT NULL DEFAULT 0.000,
    ADD COLUMN `userFirstBuy` TINYINT NOT NULL DEFAULT 0,
    ADD COLUMN `userInvitedBy` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `userLanguage` INTEGER NULL,
    ADD COLUMN `utmData` TEXT NULL,
    ADD COLUMN `wallet` DECIMAL(10, 5) NOT NULL DEFAULT 0.00000,
    ADD COLUMN `weeklyNews` SMALLINT NOT NULL DEFAULT 1,
    ADD COLUMN `weight` INTEGER NULL;
